---
- name: Install Required Packages + NZBget
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - unrar-free
    - nzbget

- name: Create Default Settings
  sudo: yes
  template: src=default.settings.nzbget.tpl dest=/home/{{server.download_user}}/.nzbget

- name: Change Ownership Of NZBget Configuration File
  sudo: yes
  file: path=/home/{{server.download_user}}/.nzbget owner={{server.download_user}} group={{server.download_user}}

- name: Add Runscripts For NZBget
  sudo: yes
  template: src=runscript.nzbget.tpl dest=/etc/init.d/nzbget


- name: Add Execute Permissions To Runscript
  sudo: yes
  file: path=/etc/init.d/nzbget state=file mode="755"
#
#- name: Create Default Settings
#  sudo: yes
#  template: src=default.settings.sickrage.tpl dest=/etc/default/sickrage
#
#- name: Add Execute Permissions To Default Settings
#  sudo: yes
#  file: path=/etc/default/sickrage state=file mode="755"
#
- name: Update Boot Sequence To Recognize NZBget
  sudo: yes
  command: update-rc.d nzbget defaults
  notify:
      - restart nzbget
#
#- name: Change SickRage ownership
#  sudo: yes
#  file: path=/home/{{server.download_user}}/.sickrage owner={{server.download_user}} group={{server.download_user}} recurse=yes
