---
server:
    packages: [vim, git, htop, nfs-kernel-server, nfs-common]
    timezone: Europe/Amsterdam
    locale: en_US.UTF-8
    download_user: downloader
sickrage:
    home: "/home/{{server.download_user}}/.sickrage"
    user: "{{server.download_user}}"