---
server:
    packages: [vim, git, htop, nfs-kernel-server, nfs-common]
    timezone: Europe/Amsterdam
    locale: en_US.UTF-8
    download_user: downloader
sickrage:
    home: "/home/{{server.download_user}}/.sickrage"
    user: "{{server.download_user}}"
couchpotato:
    home: "/home/{{server.download_user}}/.couchpotato"
    user: "{{server.download_user}}"
deluged:
    user: "{{server.download_user}}"
    group: "{{server.download_user}}"
    run_at_startup: "YES"
    logfile_location: "/var/log/deluge-daemon.log"
delugewebui:
    user: "{{server.download_user}}"
    group: "{{server.download_user}}"
    logfile_location: "/var/log/deluge-web.log"
nzbget:
  user: "{{server.download_user}}"
  download_dir: "/home/{{server.download_user}}/downloads"