---
- name: Install Required Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - git-core
    - python
    - python-cheetah

- name: SickRage Git Repository Checkout
  sudo: yes
  git: repo=https://github.com/SiCKRAGETV/SickRage.git dest=/home/{{server.download_user}}/.sickrage

- name: Initiate autoProcessTV CFG
  sudo: yes
  command: cp -a /home/{{server.download_user}}/.sickrage/autoProcessTV/autoProcessTV.cfg.sample /home/{{server.download_user}}/.sickrage/autoProcessTV/autoProcessTV.cfg

- name: Add Runscripts For SickRage
  sudo: yes
  command: cp /home/{{server.download_user}}/.sickrage/runscripts/init.debian /etc/init.d/sickrage

- name: Add Execute Permissions To Runscript
  sudo: yes
  file: path=/etc/init.d/sickrage state=file mode="u+rwx"

- name: Create Default Settings
  sudo: yes
  template: src=default.settings.sickrage.tpl dest=/etc/default/sickrage

- name: Change SickRage ownership
  sudo: yes
  file: path=/home/{{server.download_user}}/.sickrage owner={{server.download_user}} group={{server.download_user}}
