---
- name: Install Required Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - git-core
    - python
    - python-cheetah

- name: SickRage Git Repository Checkout
  sudo: yes
  git: repo=https://github.com/SiCKRAGETV/SickRage.git dest={{sickrage.home}}

- name: Initiate autoProcessTV CFG
  sudo: yes
  command: cp -a {{sickrage.home}}/autoProcessTV/autoProcessTV.cfg.sample {{sickrage.home}}/autoProcessTV/autoProcessTV.cfg

- name: Add Runscripts For SickRage
  sudo: yes
  command: cp {{sickrage.home}}/runscripts/init.debian /etc/init.d/sickrage

- name: Add Execute Permissions To Runscript
  sudo: yes
  file: path=/etc/init.d/sickrage state=file mode="755"

- name: Create Default Settings
  sudo: yes
  template: src=default.settings.sickrage.tpl dest=/etc/default/sickrage

- name: Add Execute Permissions To Default Settings
  sudo: yes
  file: path=/etc/default/sickrage state=file mode="755"

- name: Update Boot Sequence To Recognize SickRage
  sudo: yes
  command: update-rc.d sickrage defaults
  notify:
      - restart sickrage

- name: Change SickRage ownership
  sudo: yes
  file: path={{sickrage.home}} owner={{server.download_user}} group={{server.download_user}} recurse=yes
