---
- name: Install Required Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - git-core
    - python
    - python-cheetah

- name: SickRage Git Repository Checkout
  sudo: yes
  git: repo=https://github.com/SiCKRAGETV/SickRage.git dest=/home/{{ server.download_user }}/.sickrage

- name: Change SickRage ownership
  sudo: yes
  file: path=/home/{{ server.download_user }}/.sickrage owner={{ server.download_user }} group={{ server.download_user }}